language: python
python:
    - "2.7"
install: pip install -r requirements.txt
script:
    - PYTHONPATH=. python tests/unit.py
    - PYTHONPATH=. python tests/integration.py
    - PYTHONPATH=. python tests/acceptance.py
    # Add any other tests here