"""empty message

Revision ID: 2e0e5970798d
Revises: 1cbd6d358ade
Create Date: 2015-02-28 19:22:31.417720

"""

# revision identifiers, used by Alembic.
revision = '2e0e5970798d'
down_revision = '1cbd6d358ade'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
