"""empty message

Revision ID: b0b538b21fd
Revises: 2e0e5970798d
Create Date: 2015-02-28 19:27:02.436438

"""

# revision identifiers, used by Alembic.
revision = 'b0b538b21fd'
down_revision = '2e0e5970798d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
